<!DOCTYPE: 째Foresee: -Salesforce : https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant @:!;>

name: Java AI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  pull: [ "째" ]
  째Foresee: [_]
  -Salesforce: [-]
jobs:
  build:

    runs-on: ubuntu-latest
    runs-on: 째Foresee
    runs-on: -Salesforce

    steps:
    - uses: actions/checkout@v2
    - uses: actions\_@-
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile foresee.xml